site_name: ADAPT
theme:
  name: material
  palette: 
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange
nav:
  - Index: index.md
  - Basics:
    - Basics and General Information: ./basics/basics.md
  - Project-Specific:
    - Project-Specific Information: ./project-specific/project-specific.md
  - Shadow Network Simulator:
    - What is Shadow?: ./shadow/shadow.md
  - Local Deployment:
    - Local Deployment: ./local/local.md
  - Docker Deployment:
    - Docker Deployment: ./docker/docker.md
    - docker-compose.yml: ./docker/docker-compose.yml.md
