site_name: ADAPT
theme:
  name: material
  palette: 
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: purple
      accent: deep purple

    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: purple
      accent: deep purple
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
nav:
  - Index: index.md
  - Basics:
    - Basics and General Information: ./general/general.md
    - Configuring and Running a Pluggable Transport: ./general/running-a-pt.md
    - Client torrc: ./general/torrc-client.md
    - Bridge torrc: ./general/torrc-bridge.md
  - Shadow Network Simulator:
    - What is Shadow?: ./shadow/shadow.md
    - Getting started: ./shadow/getting-started.md
    - Configuring Shadow: ./shadow/configuration.md
    - This Project's Shadow Architecture: ./shadow/architecture.md
  - Local Deployment: ./local/local.md
  - Docker Deployment:
    - Docker Deployment: ./docker/docker.md
    - docker-compose.yml: ./docker/docker-compose.yml.md
    - dockerfile: ./docker/dockerfile.md
  - Python Pluggable Transport: ./ppt/ppt.md
  - Contributing to the Documentation: ./documentation/contributing.md
  - Future Work: ./future_work/future_work.md