services:
  pt-server:
    build: 
      context: ../
      dockerfile: docker/server/Dockerfile
    container_name: pt-server
    networks:
        - tornet

  pt-client:
    build:
      context: ../
      dockerfile: docker/client/Dockerfile
    container_name: pt-client
    networks:
      - tornet
    ports:
      - "9052:9052"

networks:
  tornet:
    driver: bridge
