FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get upgrade -y && apt-get install -y \
    ca-certificates \
    build-essential \
    cmake \
    findutils \
    libclang-dev \
    libc-dbg \
    libglib2.0-0 \
    libglib2.0-dev \
    make \
    netbase \
    python3 \
    python3-networkx \
    xz-utils \
    util-linux \
    gcc \
    g++ \
    git \
    curl \
    apt-transport-https \
    gnupg \
    wget && rm -rf /var/lib/apt/lists/*

RUN printf '%s\n' \
"Types: deb deb-src" \
"URIs: https://deb.torproject.org/torproject.org/" \
"Suites: noble" \
"Components: main" \
"Signed-By: /usr/share/keyrings/deb.torproject.org-keyring.gpg" \
> /etc/apt/sources.list.d/tor.sources

RUN wget -qO- https://deb.torproject.org/torproject.org/A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc | gpg --dearmor | tee /usr/share/keyrings/deb.torproject.org-keyring.gpg >/dev/null

RUN apt update && apt install tor deb.torproject.org-keyring -y

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

WORKDIR /opt
RUN git clone https://github.com/shadow/shadow.git && \
    cd shadow && \
    ./setup build --clean --test

RUN cd /opt/shadow && ./setup install

RUN cp -rn /root/.local/* /usr/local/ && \
    chmod -R +rx /usr/local/bin /usr/local/lib

ENV PATH="/root/.local/bin:${PATH}"

WORKDIR /workspace

ENTRYPOINT ["bash", "/workspace/shadow_run.sh"]